apiVersion: v1
kind: Pod
metadata:
  labels:
    label: yaml-pod
spec:
  containers:
  - name: maven
    image: maven:alpine
    command:
    - cat
    tty: true
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true
    volumeMounts:
  - name: nfs
    mountPath: "/usr/share/nginx/html"
volumes:
- name: nfs
  persistentVolumeClaim:
    claimName: nfs